spring:
  server:
  port: 8081
  manInfo:
    age: 18
    name: jason

---
spring:
  profiles: dev
  application:
    name:microsericecloud-config-dev

---
spring:
  profiles: test
  application:
    name:microsericecloud-config-test


    